import React,{useRef,useState} from 'react';
import {Moon,Phone,Mic,MessageCircle,Play,Pause} from 'lucide-react';

const tobaClips=['/audio/toba-1.mp3','/audio/toba-2.mp3','/audio/toba-3.mp3','/audio/toba-4.mp3','/audio/toba-5.mp3','/audio/toba-6.mp3'];
const alexClips=['/audio/alex-1.mp3','/audio/alex-2.mp3','/audio/alex-3.mp3','/audio/alex-4.mp3','/audio/alex-5.mp3'];
const prompts=['Good morning, Alex. Let’s find three small steps that fit your day. How did you sleep last night?','How is your energy today?','How is your body feeling — comfortable, a little stiff, or painful?','Have you completed your usual morning routine?','Thanks, Alex. What feels like one small win you could make today?','That’s enough for today. Ready to see your gentle-momentum plan?'];
const answers=[['Not very well. I woke up a few times.','I slept pretty well.'],['Around five out of ten.','I have a little more energy today.'],['My knees are a little stiff.','My body feels comfortable.'],['Not yet.','Yes, I have.'],['I’ll start with my morning routine.','I can do one small thing.'],['Finish check-in']];

export default function AudioVoiceCall({onEnd,setRisk}){
  const ringRef=useRef(null); const audioRef=useRef(null); const[mode,setMode]=useState('incoming'); const[q,setQ]=useState(0); const[muted,setMuted]=useState(false); const[playing,setPlaying]=useState(''); const[caption,setCaption]=useState('');
  const playClip=(src,onEnded)=>{const audio=audioRef.current;if(!audio)return;audio.onended=()=>{setPlaying('');if(onEnded)onEnded()};audio.src=src;setPlaying(src);audio.play().catch(()=>setPlaying(''))};
  const answerCall=()=>{if(ringRef.current)ringRef.current.pause();setMode('call');setTimeout(()=>playClip(tobaClips[0]),0)};
  const respond=(answer)=>{setCaption(answer);if(q===5){onEnd();return}const next=q+1;playClip(alexClips[q],()=>{setQ(next);playClip(tobaClips[next])});setQ(next)};
  if(mode==='incoming')return <div className="voice-shell incoming-shell"><audio ref={ringRef} src="/audio/nokia.mp3" autoPlay loop/><div className="voice-top"><span className="voice-logo"><img src="/assets/toba-logo.png" alt=""/> Toba</span><span className="voice-time">Your tiny AI for everyday wins</span></div><div className="incoming-center"><span className="incoming-kicker">MEET TOBA · YOUR DAILY RESET</span><div className="voice-orb incoming-orb avatar-orb"><img src="/assets/toba-logo.png" alt="Toba"/></div><h1>Toba is calling</h1><p>Small moves. Good energy.</p></div><div className="incoming-actions"><button className="decline" onClick={()=>{if(ringRef.current)ringRef.current.pause();setRisk(true)}}>Decline</button><button className="answer" onClick={answerCall}><Phone/> Answer</button></div></div>;
  return <div className="voice-shell"><audio ref={audioRef}/><div className="voice-top"><span className="voice-logo"><img src="/assets/toba-logo.png" alt=""/> Toba</span><span className="voice-time">00:{String(12+q*9).padStart(2,'0')}</span></div><div className="voice-center"><div className={'voice-orb speaking q'+q+' avatar-orb'}><img src="/assets/toba-logo.png" alt="Toba"/></div><span className="voice-status">{playing?`Toba is speaking…`:(muted?'Muted':'Toba is listening…')}</span><p className="voice-prompt">{prompts[q]}</p>{caption&&<span className="voice-caption">{caption}</span>}<div className="quick-replies">{answers[q].map(answer=><button key={answer} onClick={()=>respond(answer)}>{answer}</button>)}</div>{playing&&<button className="audio-replay" onClick={()=>{const a=audioRef.current;a.paused?a.play():a.pause()}}>{audioRef.current?.paused?<Play/>:<Pause/>} Audio</button>}</div><div className="voice-controls"><button onClick={()=>setMuted(!muted)}><Mic/> {muted?'Unmute':'Mute'}</button><button className="end" onClick={onEnd}><span/> End call</button><button><MessageCircle/> Captions</button></div></div>
}
